# taplo: $schema=https://json.schemastore.org/hugo.json
baseURL = 'https://franta.us'
languageCode = 'en-us'
title = "Franta's Blog"
theme = 'devise'
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; 2024, Frantisek Bartik"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        title = "About"
        url = "/about/"
        weight = -110
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        title = "Posts"
        url = "/posts/"
        weight = -100

[params]
    description = "My personal page"
    header_title = 'Frantisek "Franta" Bartik'
    header_subtitle = "Datacenter Tech | Columbus, OH"

    [params.contact]
    email = "fb@franta.us"
    [[params.social]]
        fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
        href = "http://github.com/frantathefranta"      # Link to associate with icon (http://, https://, mailto:)
    [[params.social]]
        fa_icon = "fab fa-linkedin-in fa-1x"
        href = "https://www.linkedin.com/in/frantisek-bartik-880/"
    [[params.social]]
        fa_icon = "fas fa-at fa-1x"
        href = "mailto:fb@franta.us"
